/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ExecutiveSummaryRouteImport } from './routes/executive-summary'
import { Route as IndexRouteImport } from './routes/index'

const ExecutiveSummaryRoute = ExecutiveSummaryRouteImport.update({
  id: '/executive-summary',
  path: '/executive-summary',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/executive-summary': typeof ExecutiveSummaryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/executive-summary': typeof ExecutiveSummaryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/executive-summary': typeof ExecutiveSummaryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/executive-summary'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/executive-summary'
  id: '__root__' | '/' | '/executive-summary'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExecutiveSummaryRoute: typeof ExecutiveSummaryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/executive-summary': {
      id: '/executive-summary'
      path: '/executive-summary'
      fullPath: '/executive-summary'
      preLoaderRoute: typeof ExecutiveSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExecutiveSummaryRoute: ExecutiveSummaryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
